- package.json
- webpack.config.js
> Add Enviorment plugin

- package.json
- src/bootstrap.tsx
- webpack.config.js
#5 에서 제대로 테스트 하지 못하여 수정 패치를 보냅니다.
자세한 사항은 커밋 메세지 참고 바람
> Fix webpack env

- README.md
| dimigo.in | reflation |
| :--: | :--: |
| ![Screen Shot 2020-01-03 at 23 02 49](https://user-images.githubusercontent.com/5278201/71762694-87add300-2e87-11ea-9d88-262ce9cc5cc6.png) | ![로그인](https://user-images.githubusercontent.com/5278201/71762701-a0b68400-2e87-11ea-91b0-38e79a635e4e.png) |
지금의 로그인 UI는 [dimigo.in](https://dimigo.in/auth/login)를 많은 부분을 참고하여 디자인 되었습니다. 
다행이 위 서비스는 MIT를 라이선스로 배포되고 있어 README에 부연 설명을 추가하면 됩니다.
> Add a specify description for UI of Login page

- .eslintrc
- src/app/app.tsx
- src/app/components/Checkbox.tsx
- src/app/components/Input.tsx
- src/app/components/Label.tsx
- src/app/components/Submit.tsx
- src/styles/components/Box.ts
- src/styles/components/Input.ts
- src/styles/components/Text.ts
- src/styles/components/Title.ts
This PR includes an ESLint fix commit.
> Use linaria on styling

- src/bootstrap.tsx
> Don't check session in dev server

- src/app/app.tsx
- src/app/components/Checkbox.tsx
- src/app/components/Footer.tsx
- src/app/components/Input.tsx
- src/app/components/Label.tsx
- src/app/components/Submit.tsx
- src/styles/components/Box.ts
- src/styles/components/Input.ts
- src/styles/components/Text.ts
- src/styles/components/Title.ts
- src/utils/styled.ts
- tsconfig.json
> Use styled API

- src/styles/theme.css
Footer 컴포넌트처럼 첫 화면 상에 완전히 가려지는 레이아웃을 지원하기 위해 필요합니다.
> Change #app size to min-height

- src/app/app.tsx
- src/app/components/Checkbox.tsx
> Create Checkbox style

- src/app/features/localStorage.ts
> Check localstorage before submit

- src/app/components/Input.tsx
- src/static/logout.js
- src/styles/components/Input.ts
flex 레이아웃으로 1: 9로 가로 폭을 잡았습니다.
부수적으로 (원래 없어도 될) Input 양옆의 패딩을 제거했습니다.
> Use flex in text input

- src/static/logout.js
> Delete logout script

- src/static/index.html
- src/styles/theme.css
- src/utils/reconstruct.ts
프로젝트 전용 나눔스퀘어 라운드 CDN을 구축했습니다.
크롬 확장 기능 환경에서 CSS의 `@import url()` 구문으로 파일이 로드되지 않아 `<link />` 요소로 수정했습니다.
> Update CDN with <link /> element

- package.json
- webpack.config.js
- yarn.lock
> [Minimizing For Production - webpack-contrib/mini-css-extract-plugin](https://github.com/webpack-contrib/mini-css-extract-plugin#minimizing-for-production)
close #30
> Minify bundled CSS

- src/logout.ts
- src/static/manifest.json
- webpack.config.js
> Implement Logout UI

- src/app/features/login.ts
> Remove 'next' query string

- .circleci/config.yml
- .eslintrc
- .gitignore
- package.json
- src/app/app.test.tsx
- tsconfig.json
- yarn.lock
> Setup Jest

- .eslintrc
- src/app/app.tsx
- src/app/features/login.ts
- src/app/features/loginReducer.ts
- Action 타입에 별칭 사용
- (Action에 함수를 넘기는) Thunk 패턴 사용으로 컴포넌트 내부에 dispatch 구문을 줄였습니다.
TODO : 두개의 라인에서 일어나는 타입 미스 고치기
> Improve reducer

- src/app/features/loginReducer.ts
> Declare action type from tuple

- src/app/app.tsx
- src/app/features/__mocks__/login.ts
- src/app/features/localStorage.ts
- src/app/features/login.common.ts
- src/app/features/login.ts
- src/app/features/loginReducer.ts
Redirects now handled at the component level.
Fix #64 : Dispatching correct status not work
> Prevent skip dispatch 'correct' action

- src/app/app.test.tsx
- src/app/app.tsx
- src/app/features/__mocks__/login.ts
- src/app/features/login.common.ts
- src/app/features/login.ts
- src/app/features/loginReducer.ts
> Idea from : https://github.com/reflation/extension/pull/67/#pullrequestreview-406561732
Action now have a type and payload prop.
More details about FSA convention:
https://github.com/redux-utilities/flux-standard-action
> Use Flux Standard Action convention

- src/app/app.tsx
- src/app/components/Checkbox.tsx
1. 루트 컴포넌트 및 체크박스 컴포넌트의 Props 선언을 인터페이스로 수정
2. 체크박스 컴포넌트의 타입을 더 세분화 시켰습니다.
> Update to Interface convention

- src/app/app.tsx
- src/app/components/Label.tsx
- src/app/components/Link.tsx
- src/styles/components/Box.ts
목업 그릴 때 같이 설계해둔 기능인데, 이제서야 추가하게 됐네요.
> Implement FindPassword component

- src/static/manifest.json
> Release 0.2.5

- src/app/features/loginReducer.ts
> Fix to use constant variable types in Reducer
